buildmaster: Manually revert most of buildmaster command.
This reverts the commits:
096234c299a45c89df45bc6817961d00b0b92898
cd4fae76b76006466e039e17ed37089d39e7001e
11ac94cbfcace81dbaeeaa30352f19b1059ee3e2
7ca228ae538cbf35f4a22c63999f230109a4e3c9

The changes were based on the assumption that the buildmaster command
should be run from within haikuporter. It must however always be run
from the ports tree that it manages.

diff --git a/buildmaster/bin/buildmaster b/buildmaster/bin/buildmaster
--- a/buildmaster/bin/buildmaster
+++ b/buildmaster/bin/buildmaster
@@ -1,24 +1,24 @@
 #!/bin/bash
 
-if [ -z "$BASE_DIR" ]; then
-	BASE_DIR="$(pwd)/buildmaster"
-	echo "WARNING: BASE_DIR is currently undefined. Assuming $BASE_DIR."
+BASE_DIR="$(pwd)/buildmaster"
+CONFIG_FILE="$BASE_DIR/config"
+source "$CONFIG_FILE"
+
+if [ $? -ne 0 ]
+then
+	echo "configuration file $CONFIG_FILE couldn't be sourced"
+	exit 1
 fi
 
 if [ -z "$HAIKUPORTER" ]
 then
-	HAIKUPORTER=$(which haikuporter 2>/dev/null)
-	if [ $? -ne 0 ]; then
-		echo "ERROR: HAIKUPORTER environment variable not set and haikuporter not in path"
-		exit 1
-	fi
+	echo "HAIKUPORTER environment variable not set"
+	exit 1
 fi
-
-HAIKUPORTS_TREE="$(${HAIKUPORTER} -t)"
 
 case "$1" in
 	update)
-		git -C "${HAIKUPORTS_TREE}" pull --ff-only
+		git pull --ff-only
 		if [ $? -ne 0 ]
 		then
 			echo "git pull failed, manual fixing needed"
@@ -26,8 +26,8 @@ case "$1" in
 		fi
 
 		REVISIONS_FILE="$BASE_DIR/processed_rev"
-		PREVIOUS_REVISION=$(cat "$REVISIONS_FILE" 2>/dev/null)
-		HEAD_REVISION=$(git -C "${HAIKUPORTS_TREE}" rev-parse HEAD)
+		PREVIOUS_REVISION=$(cat "$REVISIONS_FILE")
+		HEAD_REVISION=$(git rev-parse HEAD)
 
 		if [ "$PREVIOUS_REVISION" == "$HEAD_REVISION" ]
 		then
@@ -38,8 +38,8 @@ case "$1" in
 		echo "moving from $PREVIOUS_REVISION to $HEAD_REVISION"
 		"$HAIKUPORTER" --no-package-obsoletion --repository-update
 
-		PORTS_TO_BUILD=$(git -C "${HAIKUPORTS_TREE}" diff-tree -z -r --name-only \
-				--diff-filter ACMTR $PREVIOUS_REVISION..$HEAD_REVISION \
+		PORTS_TO_BUILD=$(git diff-tree -z -r --name-only --diff-filter ACMTR \
+				$PREVIOUS_REVISION..$HEAD_REVISION \
 			| xargs --null "$HAIKUPORTER" --no-package-obsoletion \
 				--no-repository-update --ports-for-files \
 				--active-versions-only 2> /dev/null \
